name: ci

on:
  push:
    branches:
      - 'devops-dev'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: user/app:latest
